---
title: "Exploratory Data Analysis, Summary Stats & Visualization"
---

## Github repositories for today

* Part 1 - [https://github.com/melindahiggins2000/N741_Lecture5_20180214](https://github.com/melindahiggins2000/N741_Lecture5_20180214) - this Github repository provides examples using the `car` package with the `Leinhardt` dataset which will help with Homework 2

* Part 2 - [https://github.com/melindahiggins2000/Lecture7Foreal](https://github.com/melindahiggins2000/Lecture7Foreal) - this Github repository covers additional examples working with `dplyr` and `ggplot2` working with a `Pesticides` dataset - this repository was adapted from N741 2017 Lecture 7.

## Exploratory Data Analysis, Summary Statistics & Visualization

Today's lecture will get you up and running working with data frames, exploring your data with summary statistics and visualizations. You will be learning the "tidyverse" way of doing things in `R` using the `dplyr` and `ggplot2` packages. Learn more about these packages at:

* `tidyverse` [https://www.tidyverse.org/](https://www.tidyverse.org/)
* `dplyr` [http://dplyr.tidyverse.org/](http://dplyr.tidyverse.org/)
* `ggplot2` [http://ggplot2.tidyverse.org/](http://ggplot2.tidyverse.org/)
* Garrett Grolemund and Hadley Wickham's book "R for Data Science" - specifically see these chapters:
    - Chapter 3: Data Visualization [http://r4ds.had.co.nz/data-visualisation.html](http://r4ds.had.co.nz/data-visualisation.html)
    - Chapter 5: Data Transformation [http://r4ds.had.co.nz/transform.html](http://r4ds.had.co.nz/transform.html)
    - Chapter 7: Exploratory Data Analysis [http://r4ds.had.co.nz/exploratory-data-analysis.html](http://r4ds.had.co.nz/exploratory-data-analysis.html)

I also encourage you to explore these courses at Datacamp:

* Introduction to the Tidyverse [https://www.datacamp.com/courses/introduction-to-the-tidyverse](https://www.datacamp.com/courses/introduction-to-the-tidyverse)
* Cleaning Data in R [https://www.datacamp.com/courses/cleaning-data-in-r](https://www.datacamp.com/courses/cleaning-data-in-r)
* Exploratory Data Analysis in R: Case Study [https://www.datacamp.com/courses/exploratory-data-analysis-in-r-case-study](https://www.datacamp.com/courses/exploratory-data-analysis-in-r-case-study)
* Data Manipulation in R with dplyr [https://www.datacamp.com/courses/dplyr-data-manipulation-r-tutorial](https://www.datacamp.com/courses/dplyr-data-manipulation-r-tutorial)
* Data Visualization with ggplot2 (Part 1), (Part 2), and (Part 3)
    - [https://www.datacamp.com/courses/data-visualization-with-ggplot2-1](https://www.datacamp.com/courses/data-visualization-with-ggplot2-1)
    - [https://www.datacamp.com/courses/data-visualization-with-ggplot2-2](https://www.datacamp.com/courses/data-visualization-with-ggplot2-2)
    - [https://www.datacamp.com/courses/data-visualization-with-ggplot2-part-3](https://www.datacamp.com/courses/data-visualization-with-ggplot2-part-3)
    

### Vicki's slides from Spring 2017

Vicki's slides from today can be viewed at [https://htmlpreview.github.io/?https://raw.githubusercontent.com/vhertzb/EDA/master/EDA.html#/](https://htmlpreview.github.io/?https://raw.githubusercontent.com/vhertzb/EDA/master/EDA.html#/)

