---
title: "Introduction, R, RStudio, Github and More"
---

## Introduction to the Course

This course will describe the concepts underlying the field of study identified as big data analytics along with its application in healthcare. The theoretical underpinnings of these concepts will be presented along with applications in healthcare, including knowledge discovery, precision medicine/nursing, and the development of targeted interventions to improve health outcomes. Commonly used methods in big data analytics will be reviewed, and the challenges related to gathering, analyzing, visualizing, and interpreting big data will be discussed. Hands-on computer laboratory experience with these techniques relevant to an identified area will be included.

## What is data science

_**Open discussion**_

## Introductory Slides

* [Lecture 1 Slides](https://github.com/melindahiggins2000/N741bigdata/raw/master/Lecture%201%2020180116.pptx) - right click and save if you wish
* [Introduction to Reproducible Research](https://github.com/melindahiggins2000/N741bigdata/raw/master/module_01.pdf) - right click to save PDF or click to view

## Software Tools and Resources

* `R` [https://cran.r-project.org/](https://cran.r-project.org/)
* `RStudio` [https://www.rstudio.com/](https://www.rstudio.com/)
* `Github` [https://github.com/](https://github.com/)
* rstudio.cloud [https://rstudio.cloud/](https://rstudio.cloud/)
* Datacamp [https://www.datacamp.com/](https://www.datacamp.com/)

## Resources

See links and information on this website under _**Resources**_ for R, RStudio, Git and Github at [https://melindahiggins2000.github.io/N741bigdata/help.html](https://melindahiggins2000.github.io/N741bigdata/help.html).

## Setting up R and RStudio

1. See [Pre R Workshop Setup Instructions](https://melindahiggins2000.gitbooks.io/a-series-of-r-workshops/content/preWorkshop/index.html) This online "Book" has information on R, installing R and RStudio, and places to get help.

2. [Youtube Video](https://www.youtube.com/watch?v=MsV5dJ2reQ4) on Installing R, RStudio and Compiling your first Rmarkdown report.

## Working with R/RStudio with GIT/Github

A key online book that is HUGELY helpful is "Happy Git and Github for the UseR" by Jenny Bryan, see [http://happygitwithr.com/](http://happygitwithr.com/).

## Rmarkdown reports

In addition to the YouTube video demonstration above, also learn more at:

* [RMarkdown](http://rmarkdown.rstudio.com/index.html)

* [Knitr examples](http://yihui.name/knitr/demo/showcase/)

* Karl Broman's website [Knitr in a Knutshell](http://kbroman.org/knitr_knutshell/) tutorial





