---
title: "Microbiome Analysis - `dada2` Tutorial"
---

## part 2 03/07/2018

* files for part 2 of the `dada2` exercise at located in the Github repo at [https://github.com/vhertzb/2018Week8](https://github.com/vhertzb/2018Week8)

* See lecture in HTML at [https://cdn.rawgit.com/vhertzb/2018Week8/master/2018Week8.html](https://cdn.rawgit.com/vhertzb/2018Week8/master/2018Week8.html)

## `dada2` exercise

* see `vhertzb` Github repo at [https://github.com/vhertzb/2018Week7](https://github.com/vhertzb/2018Week7)

* HTML file with notes [https://cdn.rawgit.com/vhertzb/2018Week7/05bff59a/2018Week7_dada2.html](https://cdn.rawgit.com/vhertzb/2018Week7/05bff59a/2018Week7_dada2.html)

## Complete Homework 3 - `dada2` prep work

The next 2 classes (lessons 7 and 8) will introduce and work through the data analysis tutorial using the `dada2` `R` package. Complete [Homework 3](https://melindahiggins2000.github.io/N741bigdata/hmwk3.html) to be sure you are prepared to work through these exercises. 

See details at [https://cdn.rawgit.com/vhertzb/2018week6/master/HW3_for_2018.html](https://cdn.rawgit.com/vhertzb/2018week6/master/HW3_for_2018.html).

## More details on `dada2` `R` Package

* `dada2` homepage [https://benjjneb.github.io/dada2/](https://benjjneb.github.io/dada2/)

## Prep Work for `dada2` Tutorial - Instructions

However, if you would like to come and work along with us through the exercises (hands-on), please come prepared with the following:

1. A laptop with R and RStudio installed:
    a. Download R [https://cran.r-project.org/](https://cran.r-project.org/)
    b. Download RStudio [https://www.rstudio.com/products/rstudio/download/#download](https://www.rstudio.com/products/rstudio/download/#download) 
    
    
2. Install these R packages ahead of time
    a. tidyverse from CRAN [https://cran.r-project.org/web/packages/tidyverse/index.html](https://cran.r-project.org/web/packages/tidyverse/index.html) 
    b. dada2 from Bioconductor [https://www.bioconductor.org/packages/release/bioc/html/dada2.html](https://www.bioconductor.org/packages/release/bioc/html/dada2.html) 
    c. phyloseq from Bioconductor [https://bioconductor.org/packages/release/bioc/html/phyloseq.html](https://bioconductor.org/packages/release/bioc/html/phyloseq.html) 
    d. ShortRead from Bioconductor [http://bioconductor.org/packages/release/bioc/html/ShortRead.html](http://bioconductor.org/packages/release/bioc/html/ShortRead.html) 


3. See setup details at [https://cdn.rawgit.com/vhertzb/2018week6/master/HW3_for_2018.html](https://cdn.rawgit.com/vhertzb/2018week6/master/HW3_for_2018.html) 

4. Open RStudio – create a new project for this dada2 exercise – put it somewhere on your hard drive with a logical location, like `"c:\dada2"`

5. Then following along with the dada2 tutorial at [https://benjjneb.github.io/dada2/tutorial.html](https://benjjneb.github.io/dada2/tutorial.html) , you will need to download the Mothur MiSeq data from this link [http://www.mothur.org/w/images/d/d6/MiSeqSOPData.zip](http://www.mothur.org/w/images/d/d6/MiSeqSOPData.zip) 

6. One you download the ZIP file, extract all of the files. There will be a subfolder called `“\MiSeq_SOP”` – copy this folder and its contents into the project folder you created above (e.g. `“c:\dada2”`)

7. Next download, these 2 files “silva_nr_v132_train_set.fa.gz” and “silva_species_assignment_v132.fa.gz” from [https://zenodo.org/record/1172783#.Wo2GM62ZMo8)https://zenodo.org/record/1172783#.Wo2GM62ZMo8](https://zenodo.org/record/1172783#.Wo2GM62ZMo8)https://zenodo.org/record/1172783#.Wo2GM62ZMo8) and put them into the `“C:\dada2\MiSeq_SOP”` directory

